config/routes.rb
Accesspostgresdatafromrails::Application.routes.draw do
  resources :railscareers

end

app/models/railscareer.rb
class Railscareer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/railscareers_controller.rb
class RailscareersController < ApplicationController
  before_action :set_railscareer, only: [:show, :edit, :update, :destroy]

  # GET /railscareers
  # GET /railscareers.json
  def index
    @railscareers = Railscareer.all
  end

  # GET /railscareers/1
  # GET /railscareers/1.json
  def show
   # @railscareer = Railscareer.find(railscarer_params)
    respond_to do |format|
      format.html
      format.json{ render :json => @railscareer }
  end
end

  # GET /railscareers/new
  def new
    @railscareer = Railscareer.new
  end

  # GET /railscareers/1/edit
  def edit
  end

  # POST /railscareers
  # POST /railscareers.json
  def create
    @railscareer = Railscareer.new(railscareer_params)

    respond_to do |format|
      if @railscareer.save
        format.html { redirect_to @railscareer, notice: 'Railscareer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @railscareer }
      else
        format.html { render action: 'new' }
        format.json { render json: @railscareer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railscareers/1
  # PATCH/PUT /railscareers/1.json
  def update
    respond_to do |format|
      if @railscareer.update(railscareer_params)
        format.html { redirect_to @railscareer, notice: 'Railscareer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @railscareer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railscareers/1
  # DELETE /railscareers/1.json
  def destroy
    @railscareer.destroy
    respond_to do |format|
      format.html { redirect_to railscareers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railscareer
      @railscareer = Railscareer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def railscareer_params
      params.require(:railscareer).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railscareers_helper.rb
module RailscareersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accesspostgresdatafromrails</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/railscareers/_form.html.erb
<%= form_for(@railscareer) do |f| %>
  <% if @railscareer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@railscareer.errors.count, "error") %> prohibited this railscareer from being saved:</h2>

      <ul>
      <% @railscareer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/railscareers/edit.html.erb
<h1>Editing railscareer</h1>

<%= render 'form' %>

<%= link_to 'Show', @railscareer %> |
<%= link_to 'Back', railscareers_path %>

app/views/railscareers/index.html.erb
<h1>Listing railscareers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @railscareers.each do |railscareer| %>
      <tr>
        <td><%= railscareer.name %></td>
        <td><%= railscareer.content %></td>
        <td><%= link_to 'Show', railscareer %></td>
        <td><%= link_to 'Edit', edit_railscareer_path(railscareer) %></td>
        <td><%= link_to 'Destroy', railscareer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Railscareer', new_railscareer_path %>

app/views/railscareers/new.html.erb
<h1>New railscareer</h1>

<%= render 'form' %>

<%= link_to 'Back', railscareers_path %>

app/views/railscareers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @railscareer.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @railscareer.content %>
</p>

<%= link_to 'Edit', edit_railscareer_path(@railscareer) %> |
<%= link_to 'Back', railscareers_path %>